### ISSUE TITLE
Custom colour schemes

### ISSUE THREAD

**Issue by cybre** [evolve-os/journal#17]
An option to change the colour scheme would be great. The app could ship with a few colour schemes by default (Monokai, Solarized (Light and Dark)).

**Comment by ryanleesipes** [comment]
I've been wanting to do this for a while. Going to mark this as an
enhancement.

**Comment by ryanleesipes** [comment]
All but Monokai are in there, I will create another issue for adding that scheme.

**Comment by zesterer** [comment]
Dunno. It should auto-detect all installed themes. If its not showing up,
it's because it's not installed.

**Comment by ryanleesipes** [comment]
Unfortunately @zesterer this isn't the case anymore. It will detect the themes, but they will not work due to the current implementation (if they are not hard-coded - change was made to accommodate glib). However, I think we need to look at how to tackle that issue before moving forward. I have some ideas, we should talk about them.

**Comment by ryanleesipes** [comment]
@cybre check out #33 it has been reopened in order to address this is a really awesome way.
